/**
 * Procedural Memory Types (3B.4)
 *
 * First-class type definitions for stored, executable procedures —
 * skills / how-to sequences distinct from semantic facts and episodic
 * events. Procedures are persisted as `entityType: 'procedure'` entities
 * with the step list encoded in `observations` as JSON.
 *
 * @module types/procedure
 */

/**
 * Atomic step in a procedure. Steps are ordered by `order` (1-indexed)
 * and may carry parameters consumed by the executor.
 */
export interface ProcedureStep {
  /** 1-indexed step order. */
  order: number;
  /** Caller-meaningful action identifier (e.g. `"http.get"`, `"db.commit"`). */
  action: string;
  /** Parameter map; values are caller-defined strings. */
  parameters: Record<string, string>;
  /** Optional fallback step to run if `action` fails (recursive). */
  fallback?: ProcedureStep;
  /** Maximum step duration in ms. Caller-enforced. */
  timeout?: number;
}

/**
 * Full procedure record. Identified by `id` (caller-supplied or
 * auto-generated by `ProcedureManager.addProcedure`).
 */
export interface Procedure {
  /** Stable identifier — used as the underlying entity name. */
  id: string;
  /** Human-readable name. */
  name: string;
  /** What the procedure accomplishes. */
  description: string;
  /** Ordered step list. */
  steps: ProcedureStep[];
  /** Free-form trigger conditions (matched by `matchProcedure`). */
  triggers?: string[];
  /** Aggregate success rate in [0, 1], updated by `refineProcedure`. */
  successRate?: number;
  /** Number of executions recorded. */
  executionCount?: number;
  /** ISO 8601 timestamps. */
  createdAt?: string;
  lastModified?: string;
}

/** Result of a `matchProcedure` call. */
export interface ProcedureMatch {
  procedure: Procedure;
  /** Match quality in [0, 1] — overlap between context tokens and triggers. */
  score: number;
}

/** Caller feedback from a single execution, used by `refineProcedure`. */
export interface ProcedureFeedback {
  /** Whether the run succeeded. */
  succeeded: boolean;
  /** Optional notes / lesson appended to the procedure observations. */
  notes?: string;
  /** ISO 8601; defaults to current time. */
  recordedAt?: string;
}
